force-app/main/default/objects/Category__c.object
<CustomObject>
    <description>Used to track the expense categories.</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c.object
<CustomObject>
    <description>To keep track of all the transactions performed between the contacts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Place or store where be performed the transaction</description>
        <inlineHelpText>Place or store where be performed the transaction</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the transation</description>
        <inlineHelpText>The amount of the transation</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billed_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>To who will be billed the transaction.</description>
        <inlineHelpText>To who will be billed the transaction.</inlineHelpText>
        <label>Billed to</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Billed to)</relationshipLabel>
        <relationshipName>Billed_to</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The category of the transaction</description>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date of the transaction</description>
        <inlineHelpText>Date of the transaction</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>A detail about the expense</description>
        <inlineHelpText>A detail about the expense</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paid_By__c</fullName>
        <description>To specify who paid the transaction.</description>
        <inlineHelpText>To specify who paid the transaction.</inlineHelpText>
        <label>Paid By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Paid_by</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/UtilityTest.cls
@IsTest
public class UtilityTest {
	public static EmailTemplate createEmailtemplate() {
		EmailTemplate emailTemplate = new EmailTemplate(developername = BillStatusSchedulable.END_MONTH_EMAIL_DEVELOPER_NAME, Name = 'Test', TemplateType = 'Text', FolderId = UserInfo.getUserId(), Subject = '[LAST_MONTH]', HtmlValue = 'DEUDOR: %DEUDOR% COBRADOR: %COBRADOR% DEUDA: %DEUDA%');
		insert emailTemplate;

		return emailTemplate;
	}

	public static List<Contact> createContacts(Integer numberOfContacts) {
		List<Contact> contactsToInsert = new List<Contact>();
		for (Integer i = 0; i < numberOfContacts; i++) {
			contactsToInsert.add(createContact('Test' + i, 'LN' + i, false));
		}

		insert contactsToInsert;

		return contactsToInsert;
	}

	public static Contact createContact(String firstName, String lastName) {
		return createContact(firstName, lastName, true);
	}

	public static Contact createContact(String firstName, String lastName, Boolean mustInsert) {
		//insert a contact
		Contact contact = new Contact(FirstName = firstName, LastName = lastName, Email = firstName + lastName + '@test.com', Birthdate = Date.today().addMonths(-20 * 12), MailingState = 'CA', OtherPostalCode = '50010');

		if (mustInsert) {
			insert contact;
		}

		return contact;
	}

	public static Account createAccount() {
		Account acc = new Account(Name = 'Test');
		insert acc;

		return acc;
	}

	public static Category__c createCategory(String name) {
		Category__c cat = new Category__c(Name = name);
		insert cat;

		return cat;
	}

	public static Transaction__c createTransaction(Account acc, Contact billedTo, Contact paidBy, Date createdDate, Category__c cat, String description, Decimal amount) {
		Transaction__c transactionToCreate = new Transaction__c(Account__c = acc.Id, Amount__c = amount, Billed_to__c = billedTo.Id, Category__c = cat.Id, Date__c = createdDate, Description__c = description, Paid_By__c = paidBy.Id);

		insert transactionToCreate;

		return transactionToCreate;
	}

	public static Profile getProfile(String profileName) {
		return [SELECT Id FROM Profile WHERE Name = :profileName];
	}

	public static User createUser(String firstName, String lastName, String profileName) {
		Profile p = getProfile(profileName);
		User u = new User(Alias = firstName + lastName, Email = firstName + lastName + '@test.com', EmailEncodingKey = 'UTF-8', LastName = lastName, LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/Los_Angeles', UserName = firstName + lastName + '@test.com');
		insert u;

		return u;
	}
}