force-app/main/default/objects/Category__c.object
<CustomObject>
    <description>Used to track the expense categories.</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user for notifications.</description>
    <inlineHelpText>The related user for notifications.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c.object
<CustomObject>
    <description>Used to track when the expense belongs to a special event like a trip.</description>
    <fields>
        <fullName>Total_spent__c</fullName>
        <label>Total spent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c.object
<CustomObject>
    <description>To keep track of all the transactions performed between the contacts.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the transation</description>
        <inlineHelpText>The amount of the transation</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billed_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>To who will be billed the transaction.</description>
        <inlineHelpText>To who will be billed the transaction.</inlineHelpText>
        <label>Billed to</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Billed to)</relationshipLabel>
        <relationshipName>Billed_to</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The category of the transaction</description>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date of the transaction</description>
        <inlineHelpText>Date of the transaction</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>A detail about the expense</description>
        <inlineHelpText>A detail about the expense</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Use if the transaction is related to a special event.</description>
        <inlineHelpText>Use if the transaction is related to a special event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid_By__c</fullName>
        <description>To specify who paid the transaction.</description>
        <inlineHelpText>To specify who paid the transaction.</inlineHelpText>
        <label>Paid By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Paid_by</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TransactionTriggerTest.cls
/**
 * @File Name          : TransactionTriggerTest.cls
 * @Description        :
 * @Author             : Luis Campos (LC)
 * @Group              :
 * @Last Modified By   : Luis Campos (LC)
 * @Last Modified On   : 12-27-2020
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    1/8/2020   Luis Campos (LC)     Initial Version
 **/
@IsTest(SeeAllData=true)
// SeeAllData required because ConnectApi.ChatterFeeds.postFeedElement is used to create Chatter post in Transaction__c trigger.
public class TransactionTriggerTest {
	static void setupTestData() {
		List<Event__c> eventsToCreate = new List<Event__c>();
		List<Transaction__c> transactionsToCreate = new List<Transaction__c>();

		Contact con = UtilityTest.createContact('CT1', 'LT1');
		Category__c category = UtilityTest.createCategory('Category Test');

		for (Integer i = 0; i < 3; i++) {
			eventsToCreate.add(new Event__c(Name = 'Event Test ' + i));
		}

		insert eventsToCreate;

		for (Integer i = 0; i < 50; i++) {
			transactionsToCreate.add(new Transaction__c(Category__c = category.Id, Event__c = eventsToCreate.get(0).Id, Paid_By__c = con.Id, Amount__c = 200.00, Billed_to__c = con.Id, Date__c = System.today(), Description__c = 'Desc Test'));
		}

		for (Integer i = 0; i < 5; i++) {
			transactionsToCreate.add(new Transaction__c(Category__c = category.Id, Event__c = eventsToCreate.get(1).Id, Paid_By__c = con.Id, Amount__c = 200.00, Billed_to__c = con.Id, Date__c = System.today(), Description__c = 'Desc Test'));
		}

		insert transactionsToCreate;
	}
	@IsTest
	static void testEventAmountCalculation() {
		TransactionTriggerTest.setupTestData();
		Test.startTest();
		Event__c event0 = [SELECT Id, Total_spent__c FROM Event__c WHERE Name = 'Event Test 0' LIMIT 1];
		Event__c event1 = [SELECT Id, Total_spent__c FROM Event__c WHERE Name = 'Event Test 1' LIMIT 1];
		Event__c event2 = [SELECT Id, Total_spent__c FROM Event__c WHERE Name = 'Event Test 2' LIMIT 1];

		Test.stopTest();

		System.assertEquals(50 * 200, event0.Total_spent__c, 'The Total spent for this event must be ' + 50 * 200.00);
		System.assertEquals(5 * 200, event1.Total_spent__c, 'The Total spent for this event must be ' + 5 * 200.00);
		System.assertEquals(null, event2.Total_spent__c, 'The Total spent for this event must be empty');
	}

	@IsTest
	static void testEventAmountCalculation2() {
		TransactionTriggerTest.setupTestData();
		Test.startTest();
		Event__c theEvent = [SELECT Id, Total_spent__c FROM Event__c WHERE Name = 'Event Test 0' LIMIT 1];
		List<Transaction__c> transactionsToDelete = [SELECT Id FROM Transaction__c WHERE Event__c = :theEvent.Id LIMIT 25];

		delete transactionsToDelete;

		Event__c event0 = [SELECT Id, Total_spent__c FROM Event__c WHERE Name = 'Event Test 0' LIMIT 1];
		System.assertEquals(25 * 200.00, event0.Total_spent__c, 'The Total spent for this event must be ' + 25 * 200.00);

		List<Transaction__c> transactionsToUpdate = new List<Transaction__c>();
		for (Transaction__c trans : [SELECT Id FROM Transaction__c WHERE Event__c = :theEvent.Id]) {
			trans.Amount__c = 2.00;
			transactionsToUpdate.add(trans);
		}

		update transactionsToUpdate;

		Event__c eventU = [SELECT Id, Total_spent__c FROM Event__c WHERE Name = 'Event Test 0' LIMIT 1];
		System.debug('LCDebug: eventU ' + eventU);
		System.assertEquals(25 * 2.00, eventU.Total_spent__c, 'The Total spent for this event must be ' + 25 * 2.00);

		Test.stopTest();
	}

	@IsTest
	static void postToChatterWhenDebt() {
		Contact con1 = UtilityTest.createContact('C1', 'L1');
		Contact con2 = UtilityTest.createContact('C2', 'L2');
		User u1 = UtilityTest.createUser('C1', 'L1', 'Standard User');
		User u2 = UtilityTest.createUser('C2', 'L2', 'Standard User');
		con1.User__c = u1.Id;
		update con1;
		con2.User__c = u2.Id;
		update con2;

		Category__c category = UtilityTest.createCategory('Cat 1');

		Test.startTest();
		Transaction__c trx = UtilityTest.createTransaction(null, con1, con2, System.today(), category, 'TEST', 200.00);
		Test.stopTest();

		System.assertEquals(true, trx != null, 'Transactions must be created correctly.');
		FeedItem post = [SELECT Id, Body, IsRichText, Type FROM FeedItem WHERE ParentId = :trx.Id LIMIT 1];
		System.assertEquals(post.Body, '@L1, C2 L2 just created this transaction billed to you for 200.00 corresponding to TEST', 'Chatter post body must be correctly setted.');
		System.assertEquals(false, post.IsRichText, 'Chatter post must not be rich text');
		System.assertEquals('TextPost', post.Type, 'Chatter post type must be TextPost');
	}
}