force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Transaction__c.object
<CustomObject>
    <description>To keep track of all the transactions performed between the contacts.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the transation</description>
        <inlineHelpText>The amount of the transation</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billed_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>To who will be billed the transaction.</description>
        <inlineHelpText>To who will be billed the transaction.</inlineHelpText>
        <label>Billed to</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Billed to)</relationshipLabel>
        <relationshipName>Billed_to</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid_By__c</fullName>
        <description>To specify who paid the transaction.</description>
        <inlineHelpText>To specify who paid the transaction.</inlineHelpText>
        <label>Paid By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Paid_by</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateExpenseExtension.cls
public with sharing class CreateExpenseExtension {

    
    ApexPages.StandardController controller;
    public Transaction__c transactionItem {get; set;}
    public List<Contact> contacts {get;set;}
    public List<String> selectedContacts {get;set;}
    public List<SelectOption> contactsOption {get;set;}
    public Double billedToDiana {get;set;}
    public Double billedToLuis {get;set;}
    
    public CreateExpenseExtension() {
        System.debug('Create Expense');
        transactionItem = new Transaction__c();
        contactsOption = new List<SelectOption>();
        selectedContacts = new List<String>();
        
        String userName = UserInfo.getUserName();
        User activeUser = [Select Email From User where Username = : userName limit 1];
        String userEmail = activeUser.Email;
        System.debug(userEmail);

        contacts = [SELECT Id, Name, Email FROM Contact WHERE Active__c = true ORDER BY Name ASC];
        
        for(Contact contact : contacts){
            contactsOption.add(new SelectOption(contact.Id, contact.Name));
            if(contact.Email == userEmail){
                transactionItem.Paid_By__c = contact.Id;
            }
        }
    }

    public void Save(){
    
     try{   
             
        // insert payincrease;
        String billedToDiana = Apexpages.currentPage().getParameters().get('billedToDiana');
        String billedToLuis = Apexpages.currentPage().getParameters().get('billedToLuis');

        Transaction__c transactionForLuis = transactionItem.Clone(false, true);
        Transaction__c transactionForDiana = transactionItem.Clone(false, true);
        
        transactionForLuis.Amount__c = decimal.valueOf(billedToLuis);
        transactionForDiana.Amount__c = decimal.valueOf(billedToDiana);
        transactionForLuis.Billed_to__c = '0033j00003CIp7hAAD';
        transactionForDiana.Billed_to__c = '0033j00003CIp8LAAT';
        
        List<Transaction__c> transactionsToCreate = new List<Transaction__c>();
        transactionsToCreate.add(transactionForLuis);
        transactionsToCreate.add(transactionForDiana);
        
        insert transactionsToCreate;
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Expenses created!'));

     }
     
     catch (Exception ex) {
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ex.getMessage()));
         system.debug(ex);
     }
    } 
}