force-app/main/default/objects/Event__c.object
<CustomObject>
    <description>Used to track when the expense belongs to a special event like a trip.</description>
    <fields>
        <fullName>Total_spent__c</fullName>
        <label>Total spent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c.object
<CustomObject>
    <description>To keep track of all the transactions performed between the contacts.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the transation</description>
        <inlineHelpText>The amount of the transation</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Use if the transaction is related to a special event.</description>
        <inlineHelpText>Use if the transaction is related to a special event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TransactionHelper.cls
/**
 * @File Name          : TransactionHelper.cls
 * @Description        :
 * @Author             : Luis Campos (lucam75@gmail.com)
 * @Group              :
 * @Last Modified By   : Luis Campos (lucam75@gmail.com)
 * @Last Modified On   : 1/8/2020, 7:38:16 PM
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    1/8/2020   Luis Campos (lucam75@gmail.com)     Initial Version
 **/
public class TransactionHelper {
	public static List<Event__c> calculateAmountPerEvent(List<Transaction__c> transactions) {
		List<Event__c> eventsToUpdate = new List<Event__c>();
		try {
			if (transactions != null && transactions.size() > 0) {
				Set<Id> eventIds = new Set<Id>();

				for (Transaction__c record : transactions) {
					eventIds.add(record.Event__c);
				}

				if (!eventIds.isEmpty()) {
					for (AggregateResult ar : [SELECT Event__c, SUM(Amount__c) FROM Transaction__c WHERE Event__c IN :eventIds AND Event__c != '' GROUP BY Event__c]) {
						eventsToUpdate.add(new Event__c(Id = (Id) ar.get('Event__c'), Total_spent__c = (Double) ar.get('expr0')));
					}
				}
			}
		} catch (Exception e) {
		}

		return eventsToUpdate;
	}
}