force-app/main/default/objects/Transaction__c.object
<CustomObject>
    <description>To keep track of all the transactions performed between the contacts.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the transation</description>
        <inlineHelpText>The amount of the transation</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billed_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>To who will be billed the transaction.</description>
        <inlineHelpText>To who will be billed the transaction.</inlineHelpText>
        <label>Billed to</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Billed to)</relationshipLabel>
        <relationshipName>Billed_to</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date of the transaction</description>
        <inlineHelpText>Date of the transaction</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>It_is_debt__c</fullName>
        <formula>Billed_to__c !=  Paid_By__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>It is debt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Paid_By__c</fullName>
        <description>To specify who paid the transaction.</description>
        <inlineHelpText>To specify who paid the transaction.</inlineHelpText>
        <label>Paid By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Paid_by</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CurrentStatusUtils.cls
public with sharing class CurrentStatusUtils {
	@AuraEnabled
	public static List<AggregateResult> getBills(String yearMonth) {
		List<AggregateResult> data = new List<AggregateResult>();
		if (String.isNotBlank(yearMonth)) {
			List<String> separated = yearMonth.split('-');
			Integer year = Integer.valueOf(separated.get(0));
			Integer month = Integer.valueOf(separated.get(1));

			if (Schema.sObjectType.Transaction__c.isQueryable()) {
				String query = 'SELECT SUM(Amount__c), Paid_By__r.Name Paidby, Paid_By__r.Email PaidByEmail, Billed_to__r.Name BilledTo FROM Transaction__c WHERE CALENDAR_MONTH(Date__c) = :month and CALENDAR_YEAR(Date__c) = :year and It_is_debt__c = true GROUP BY Billed_to__r.Name, Paid_By__r.Name, Paid_By__r.Email';
				data = Database.query(query);
			}
		}

		return data;
	}
}